### ISSUE TITLE
Configuration file location

### ISSUE THREAD

**Issue by pjpalomaki** [Axadiw/MFIGamepadFeeder#10]
Hey, sorry, I'm probably being daft, but can't find the location of the application folder anywhere! Would like to change the config file.

Edit: Found it, had to search it under user/AppData/Local .. But why is there two separate config folders, both having same file?

Is there a logical way that the config file works? Am I right in assuming that the item order determines mapping? At the moment, in Xbox 360 controller supported games, my nimbus shoulder triggers aren't working at all (shoulder buttons do fine) and I would like to use the Menu button as Start button instead of Select as it is now, how would I achieve this? I know that I could use x360ce but I have more than one other controller and sometimes I use them and sometimes not.. would rather just do these changes in the config.

Thanks,
PJ

**Comment by Axadiw** [comment]
Instead of explaining internal structure of mapping files I've included editor inside MFI Gamepad Feeder app. 

It should be much easier now to edit mappings :)
