### ISSUE TITLE
PXN Speedy Support

### ISSUE THREAD

**Issue by kennethted** [Axadiw/MFIGamepadFeeder#12]
I got a pretty unheard MFi certified controller which is PXN Speedy https://afterpad.com/mficontrollers/pxn_speedy which is really great for playing on the iPad Pro, and so then I thought if I can use this controller on my PC that would be awesome, can you add support for this controller? Or a way to create my own configuration? Thanks!

**Comment by Axadiw** [comment]
In 2.0 version of the app I've included gamepad mapping editor, that you can use to add support for PXN Speedy.

If you've have any working mappings, please share them via pull request
