### ISSUE TITLE
Can't edit the button

### ISSUE THREAD

**Issue by tengkualif97** [Axadiw/MFIGamepadFeeder#13]
I follow your step correctly and it works but when i want to edit the controller button in Pro evolution soccer settings it keep replace all of the buttons with slider but i didn't click any button at the controller. its like the slider button always click itself.
![capture](https://cloud.githubusercontent.com/assets/20646451/17109744/e02403ec-52cb-11e6-955a-fdd19aa78003.PNG)

**Comment by mits3** [comment]
Same issue here

**Comment by Axadiw** [comment]
Please try with the 2.0 version of the app. If necessary you can edit device mappings by using internal editor
