### ISSUE TITLE
HORIPAD ULTIMATE wrong assignment

### ISSUE THREAD

**Issue by cpoetter** [Axadiw/MFIGamepadFeeder#2]
I tried to use your little app with the HORIPAD ULTIMATE. It works so far, just that the buttons are wrong assigned. If I press the A my computer thinks its the Y, etc... Can you change that somehow? Or what could I do? Thanks a lot for your help!

**Comment by Axadiw** [comment]
Hi, 

yes, it's possible to change keys assignment, but I haven't created any particular tool with GUI for creating new key layouts.

You can create new config file (basing on the original Nimbus.mficonfiguration file) with new keys assignment. If you'd have layout for Horipad Ultimate, please share it, so I'll add it the the master

**Comment by Axadiw** [comment]
In 2.0 there is included mapping editor, so feel free to use it to edit keys assignments
