### ISSUE TITLE
It won't work

### ISSUE THREAD

**Issue by lydomo** [Axadiw/MFIGamepadFeeder#21]
the MFI Gamepad Feeder wont work on my computer

**Comment by Axadiw** [comment]
You must give more info about your issue:
- what problem are you experiencing exactly
- what's your computer specification (especially is it 32 bit or 64 bit version of Windows, and type of your gamepad)
- which version of MFIGamepadFeeder have you installed (32bit or 64bit)?

More instructions how to report issues here: https://coenjacobs.me/2013/12/06/effective-bug-reports-on-github/

**Comment by lydomo** [comment]
My computer says "MFI Gamepad Feeder has stopped working"
64 bit version of windows
Gamepad: Steelseries Nimbus
64 bit of MFIGamepadFeeder

**Comment by Axadiw** [comment]
Please give me log from this crash (it should be available in windows event logger).

With this amount of information you've provided I'm not able to diagnose the problem.

**Comment by NicholasParry** [comment]
Having the same issue, where are the logs stored?

**Comment by Axadiw** [comment]
I haven't implemented any sophisticated log management tool, but I guess that something should be captured in Widows Event Logger.

Here's some online tutororial I've found about it on google: http://www.howtogeek.com/school/using-windows-admin-tools-like-a-pro/lesson3/

Please add all detail about it issue you'd find.

I'll implement something like https://github.com/soygul/NBug in the future - this will simplify whole flow of submitting issues like this one

**Comment by Axadiw** [comment]
I've created 2.0.2 version that includes nBug (https://github.com/Axadiw/MFIGamepadFeeder/releases/tag/2.0.2).

Now, after crash, app should create "Exception_xxx" zip file in the directory of MFIGamepadFeeder.
Could you reporoduce your crashes, and attach generated zip files in this issue?

**Comment by lydomo** [comment]
Log Name:      Application
Source:        .NET Runtime
Date:          1/4/2017 10:18:25 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      LAPTOP-MK25J4VG
Description:
Application: MFIGamepadFeeder.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.

**Comment by Axadiw** [comment]
ok, but can you try to reproduce this issue on 2.0.2, and send me zip file with the log like I've written in previous post?
