### ISSUE TITLE
Steelseries Stratus XL for iOS Support

### ISSUE THREAD

**Issue by Beshington** [Axadiw/MFIGamepadFeeder#22]
Are you able to add support for Steelseries stratus XL Game-pad for iOS?
I have done research but I cannot find out if it uses HID mode.
The controller itself connects to the computer and is recognized as a controller but does not show up in MFIgamepadfeeder 1.0 (vJoy version) or 2.0 and it doesn't work in any video games/steam.

Thanks for the great application,

-Ben

EDIT:
I just tried and it doesnt work with a usb cable either

**Comment by Axadiw** [comment]
Unfortunately, if MFIGamepadFeeder cannot see your gamepad, it means that it doesn't have required HID interface. 

Maybe some time in the future they will add HID support in firmware update, but for now there's nothing we can do :(
