### ISSUE TITLE
MFIGamepadFeeder does not see controller 

### ISSUE THREAD

**Issue by mordaskyt** [Axadiw/MFIGamepadFeeder#23]
I am able to pair the Nimbus Steelseries with windows 10, it sees the gamepad but of course does not forward any keypresses. I installed the 64bit version of the MFIGamepadFeeder software and restarted. the software opens fine, stating that the xbox bus is installed and running but it does not see my controller.

**Comment by Axadiw** [comment]
Have you paired your gamepad with PC via bluetooth or cable?

Could you try to open mappings editor, select your gamepad and check if anything changes in "Preview" section after you press buttons on the gamepad?

**Comment by tictactoes** [comment]
I have this same issue. In my case the Nimbus Steelseries is paired over Bluetooth without problem, but it does not show up in MFIGamepadFeeder. I tried opening the mappings editor like you suggested. There I can select the gamepad and button presses do register in the preview section.

**Comment by Axadiw** [comment]
What do you mean by `it does not show up in MFIGamepadFeeder` ? 

You can't don't see your gamepad in the list in main application window? Or there is a problem after pressing "start" button?

Could you share a contants of log window from main window (or screenshot of it)?

**Comment by tictactoes** [comment]
I mean that the gamepad does not show up in the list in the main application window. Nothing shows up in that list. Pressing the start button does work. Where can I find a log file?

**Comment by Axadiw** [comment]
That's strange - "mappings window" is using the same mechanism for feeding gamepads list as "main window".

Have your tried to relaunch the application, and than check if the gamepad is visible there?

**Comment by tictactoes** [comment]
Ok, turns out it works just fine as long as you select the gamepad in the main window *before* pressing start. My bad.
