### ISSUE TITLE
Hey, having trouble with PXn speedy controller.

### ISSUE THREAD

**Issue by Geits** [Axadiw/MFIGamepadFeeder#24]
Hey,

is it possible to connect PXN SPeedy controller to pc? 
It pairs with bluetooth, but does not show up in MFI gamepad feeder gamepad devices list. 

Best regards,
Geits :)

**Comment by Axadiw** [comment]
If it doesn't show up on MFI gamepad feeder devices it's most likely that this gamepad doens't support `HID` interface that is required.

Unfortunately I cannot do much about this issue, maybe manufacturer would add `HID` in some kind of firmware upgrade?
