### ISSUE TITLE
Xbox bus not installed

### ISSUE THREAD

**Issue by mdagen** [Axadiw/MFIGamepadFeeder#25]
Hello,

I I have been unable to get this to work. The controller is paired in bluetooth, the controller is detected in the feeder, but I get Xbox bus not installed after clicking start.

I am running Windows 10 via bootcamp.

![mfi](https://cloud.githubusercontent.com/assets/8829519/21986827/fa58a9de-dbce-11e6-955a-f94a00e0c2e6.jpg)

Any assistance you could provide would be appreciated!

**Comment by Axadiw** [comment]
Have you installed any other software that is using `ScpVBus`, besides MFIGamepadFeeder? 
For eg.: http://ds4windows.com (software for using PS4 controllers on PC) ?

**Comment by mikumi** [comment]
@Axadiw I also get the same error. I don't think I have any other relevajt software installed. Plain Bootcamp partition, Windows 10, Steam. 

Any ideas I could try? :-)

**Comment by mikumi** [comment]
For the record: Simply reinstalling MFIGamepadFeeder solved the issue.
