### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by SizemoreSystem** [Axadiw/MFIGamepadFeeder#28]
I would like to have this available on Linux.

**Comment by Axadiw** [comment]
Unfortunately this project includes so many dependencies that are Windows only (ScpVBus, whole Hid stack etc...) that support for linux would require writing this project completely from scratch, that I cannot support for now.

If anyone would be interested in developing such support, let me know.

**Comment by SizemoreSystem** [comment]
Alright, thanks!

**Comment by tristan-k** [comment]
What a bummer! Does someone know if there is similar project for linux in the making?
