### ISSUE TITLE
Crashes when MSI Afterburner is open

### ISSUE THREAD

**Issue by Zentrik** [Axadiw/MFIGamepadFeeder#29]
Crashes when MSI Afterburner is open. 

You can start mfigamepad, start your controller and then load msi afterburner but no other way.

**Comment by Axadiw** [comment]
Do you have any crash reports from nBug? They should be located in MFIGamepadFeeder root directory in Exception_xxx files

**Comment by Zentrik** [comment]
Don't see Exception_xxx files in C:\Program Files (x86)\MFIGamepadFeeder

**Comment by Zentrik** [comment]
If you add MFIGamepadFeeder.exe to rtss and set detection to none mfigamepadfeeder works fine.
