### ISSUE TITLE
Hmmm not work on Windows 10  and Nimbus Firmware to v1.6.4.1

### ISSUE THREAD

**Issue by StarKnightmanu** [Axadiw/MFIGamepadFeeder#3]
Unfortenly it didn't work with the Nimbus. 
Perhabs because I have updated the Nimbus Firmware to v1.6.4.1

**Comment by Axadiw** [comment]
Could you describe what problems are occuring to you?

**Comment by StarKnightmanu** [comment]
![image](https://cloud.githubusercontent.com/assets/7762728/12377437/9f2c3cda-bd1e-11e5-9d9d-07257f3f3814.png)

Connect the Nimbus to the PC via lighting cable

I start vJoyConf (2.1.6)
Make the settings as you have said in your screenshot (deselect Z Axis...)
Start MFI Feeder
Select the Nimbus
Select Nimbus config
refresh it

thats it

But no signals in the vJoy Monitor. Look a my picture? Do I forgot something?

Thanks for help!

**Comment by StarKnightmanu** [comment]
would it in principal, when it work, also work via bluetooth?

**Comment by Axadiw** [comment]
This application is intented to use via Bluetooth.

Coule you check it again when the gamepad isn't connected via cable, but when it's added via Windows "Devices -> luetooth" window?

**Comment by Axadiw** [comment]
I've checked that after plugging the Nimbus via the Lightning cable it's indeed recognized as "Steelseries Nimbus" device (actually I haven't noticed that before :)), but it isn't sending any HID-compatibile commands during button presses.

I guess that this device will work only via Bluetooth

**Comment by StarKnightmanu** [comment]
äääähm - it works via bluetooth! :) 
Sorry stupidness on my side! Thanks for the help and this great tool!

**Comment by Axadiw** [comment]
No problem. Thanks for highlighting this issue. I'll update readme :)
