### ISSUE TITLE
Failed to check if controller is plugged in (no such device)

### ISSUE THREAD

**Issue by wings103** [Axadiw/MFIGamepadFeeder#32]
Hi,
I can connect my Nimbus Gamecontroller via Bluetooth to my desktop pc just fine. After that I do everything in the correct order but as I click start, MFI Feeder tells me the following:

28.07.2017 14:19:47: XBox bus not installed (NoSuchDevice)
28.07.2017 14:19:47: Failed to check if controller plugged in 1 (NoSuchDevice)!
28.07.2017 14:19:47: Failed to check if controller plugged in 1 (NoSuchDevice)!
28.07.2017 14:19:47: Failed to check if controller plugged in 1 (NoSuchDevice)!

I tried out some things (deinstalled the Programm, made sure I did everything in the right order, updated drivers) but nothing seems to help... 

I hope you can help me out with this because I have been waiting for a programm like MFI Feeder for years...

**Comment by milesertl** [comment]
I had the same exact problem. i solved it by downloading the 64 bit version. you can get it [here](https://axadiw.github.io/MFIGamepadFeeder/)

**Comment by wings103** [comment]
Holy... it worked. Thanks a lot !!

**Comment by milesertl** [comment]
yep np

**Comment by PCurd** [comment]
I'm having the same error but am running 32 bit windows (tablet only supports 32bit) so I can't install the x64 version. Is there another fix?
