### ISSUE TITLE
dpad support - Nimbus

### ISSUE THREAD

**Issue by mrsmr2** [Axadiw/MFIGamepadFeeder#4]
Hi

Fantastic tool.  Working fine in Win7 using a Nimbus apart from the dpad.  Is dpad support able to be added, or is it vJoy limitation?

Thanks

**Comment by Axadiw** [comment]
DPad is working and supported by MFIGamepadFeeder. Have you sure that you've configured vJoy correctly in the vJoyConf tool ?

**Comment by mrsmr2** [comment]
Hi.  I have the POV Hat Switch set to Continuous 0 whereas your screenshot is set to 1.

I can't check this until tomorrow but apologies if it's a user error by me - I should have read the instructions more carefully.

Thanks

**Comment by Axadiw** [comment]
No problem, please tell us tomorrow if this fixed your issue

**Comment by mrsmr2** [comment]
Sorry, my mistake.  POV set to 1 (instead of 0) switches the dpad on.

Thanks
