### ISSUE TITLE
Not an issue. Config change to be 360 compatible

### ISSUE THREAD

**Issue by mrsmr2** [Axadiw/MFIGamepadFeeder#5]
Hi

I've experimented with the config file and changed it to map the buttons to match the 360's.

In Nimbus.mficonfiguration, alter the button order to (previously was 1, 2, 3, 4):

```
{
  "Type": 1,
  "InvertAxis": null,
  "ConvertAxis": null,
  "TargetUsage": null,
  "TargetButtonId": 2
},
{
  "Type": 1,
  "InvertAxis": null,
  "ConvertAxis": null,
  "TargetUsage": null,
  "TargetButtonId": 3
},
{
  "Type": 1,
  "InvertAxis": null,
  "ConvertAxis": null,
  "TargetUsage": null,
  "TargetButtonId": 1
},
{
  "Type": 1,
  "InvertAxis": null,
  "ConvertAxis": null,
  "TargetUsage": null,
  "TargetButtonId": 4
},
```

I normally use my 360 controller when out and about but the dpad is terrible.  I can now use my Nimbus controller for both ios and PC games, plus have a working dpad.

Fantastic tool.

Thanks very much

**Comment by Axadiw** [comment]
Great, thanks.

Could you create pull request from this, so I'd merge it to the master branch?

**Comment by mrsmr2** [comment]
Yes, I will do.  Just need to read what I've got to do.
