### ISSUE TITLE
Axis buttons do not work

### ISSUE THREAD

**Issue by ilnow33** [Axadiw/MFIGamepadFeeder#57]
Thanks for making this awesome program! One thing I notice is that with the Steelseries Nimbus the 18 numbers do not include either the left or right axis buttons. I tried adding them but I couldn't get it to work. Is there anyway to include these two buttons in the keyboard mapping so that pressing down on axis will work as a button? They show as an option (Left Stick button or Right Stick button) but I can't get them to work...

**Comment by b1u6** [comment]
The old Nimbus doesn't have pressable sticks

**Comment by ilnow33** [comment]
> The old Nimbus doesn't have pressable sticks

That explains it! Thanks
