### ISSUE TITLE
One of the button can't work for steam games

### ISSUE THREAD

**Issue by duoho** [Axadiw/MFIGamepadFeeder#6]
Hi,
    Thanks for your great tool for people who use mfi controller first!
I also using nimbus +  MFIGamepadFeeder and work fine with x360ce. (every button can be detected in x360ce)
however, in my steam game "street fighter IV", one of the button can't be detect. (the r2 button, which may mapped to "slider2" on vjoy)
May I know if you have any suggestions about this?
Many Thanks.

Duo

**Comment by Axadiw** [comment]
Hi,

Is this R2 button recognized by the x360ce ? If so, that probably an issue with x360ce

**Comment by b23prodtm** [comment]
Hi, I also experienced this issue with PES. L2 trigger is not reconized and the buttons ABXY changed of place. I don't use x360ce.

**Comment by Axadiw** [comment]
In 2.0 you don't have to use x360ce, because Xbox 360 controller are emulated by MFI Gamepad Feeder app automatically
