### ISSUE TITLE
Wont run on windows 10 on asus vivotab note 8

### ISSUE THREAD

**Issue by manoflinux** [Axadiw/MFIGamepadFeeder#7]
Wont run on windows 10 on asus vivotab note 8.
I tried it on window 8.1 on my desktop and it ran and my duo gamer was able to pair via bluetooth and it showed up in the list, but just didn't work as far as the windows joystick tests, no movement, no buttons. 

But on windows 10, I got vjoy installed and configured, but your program would not run, it did not give me an error message. It just did nothing. 
Ran it, no window, no error message, nothing. 

any ideas? could it be the bluetooth chipset on the Asus? I am grasping at straws.

**Comment by Axadiw** [comment]
Unfortunately I without any error logs I cannot tell you why the app isn't working. Have you check Windows Event Viewer, if there are any error messages there?

If not - maybe you can compile the app on your own, and than you'll receive the error message?

**Comment by CarlosVAzevedo** [comment]
The same here.
New hardware. Latest version of windows.
When I run it, what appears to be an icon blinks on the taskbar but vanishes. Then nothing. Tried many times. Uninstalled and installed again.
And there is nothing in the event viewer...
Any clues?
