### ISSUE TITLE
Is Bluetooth required?

### ISSUE THREAD

**Issue by binarymango** [Axadiw/MFIGamepadFeeder#9]
Hi,

I'd love to use my Nimbus on Windows 10, and I followed all the instructions and at the end the Feeder says "Successfully initialized gamepad", but I can't get the vJoy monitor or any games to recognize the controller. I'm not using it via bluetooth, but instead plugged-in to my PC via lightning-to-USB. Is this the issue? Does it require bluetooth to work?

Thanks!

Jeff

**Comment by Axadiw** [comment]
Unfortunately this software will work only via bluetooth
